apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: huzaifaabbasi1122/react:tagVersion
      ports:
        - containerPort: 3000